### ISSUE TITLE
Define clearely the content types (archetypes and content)

### ISSUE THREAD

**Issue by hugurp** [internet4000/portfolio-hugo-starter#2]
- what are the available fields in a project content
- how are images stored and displayed? Should it be in the front-matter? in the content?
- should there be categories and tags?
- more more more

**Comment by oskarrough** [comment]
Is it this? https://github.com/internet4000/portfolio-hugo-theme/blob/453c4de4eb0a12a3ea65d42021b4e7e8572731c6/static/admin/config.yml

In my opinion there should be taxonomies but it can also come later.

We have an `image` field in the front-matter but I see it's not working with Netlify yet. Have to rename `thumbnail` to `image`.

**Comment by hugurp** [comment]
I think today we decided to go, and implemented the following:

- hugo archetypes are left unused since they are only used by the command line users, using `hugo new $$content-type$$`.
- all content types are defined by the theme netlify-cms config file, which beconmes the documentation for command line user about what field can be used in the front matter of each content type
