### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by hugurp** [internet4000/portfolio-hugo-starter#3]
Define the installation process for a end user.

Should be thought as:
- create Github account + Netlify account
- one click clones the good repo (with cms and mockup content) to their Github account, with the good Read me and introduction + sets up Netlify deploy pipeline
- user should have easy access to the correct doc to setup custom domain name
- etc.

**Comment by oskarrough** [comment]
- Deploy this repo: https://app.netlify.com/start/deploy?repository=https://github.com/internet4000/portfolio-hugo-starter
- Custom domains: https://www.netlify.com/docs/custom-domains/

If you try to deploy without a Netlify or GitHub account it'll allow you to do so in the process. But it's probably easier to recommend people to sign up first, then click the deploy link?

**Comment by hugurp** [comment]
This is done, everything is in the repo
